Repository Ureka-High-Five/recommender-server, pull requests merged in 2025-07, with the labels that each got.

#35 Feat[#28] : RabbitMQ에서 받은 메세지를 바탕으로 유저 선호 가중치를 업데이트하는 기능 추가
  app/repositories/user_weight_repository.py
  app/services/consumer.py
  app/services/user_service.py
Labels: feat

#37 Feat[#29]: 하루 한 번 가중치 resize
  .env.local
  .github/workflows/ci.yml
  app/enum/action_type.py
  app/main.py
  app/repositories/action_log_repository.py
  app/repositories/postgresql/content_repository.py
  app/repositories/user_weight_repository.py
  app/router/user.py
  app/services/scheduler_service.py
  app/services/user_service.py
  app/services/weight_strategy.py
  app/settings/local.py
  app/util/weight_aging.py
  requirements.txt
Labels: feat

#38 Feat[#36] FastAPI에서 Redis에 유저 벡터 값 저장
  .env.local
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  app/main.py
  app/services/redis.py
  app/settings/local.py
  requirements.txt
Labels: feat

#54 Refactor[#44] : 유저 가중치 업데이트 로직 리팩토링
  .env.local
  app/main.py
  app/repositories/user_weight_repository.py
  app/services/consumer.py
  app/services/user_service.py
Labels: feat, refactor

#55 Feat[#45] : User Vector 계산 기능 추가
  app/models/db_w2v_mapper.py
  app/models/word2vec_util.py
  app/repositories/user_weight_repository.py
  app/services/consumer.py
  app/services/user_service.py
Labels: fix, feat, refactor

#59 Feat[#58]: 스케줄링 시 사용자 벡터 계산 후 레디스에 저장
  app/services/scheduler_service.py
Labels: feat

#62 Feat[#61] 계산된 유저 벡터값 redis에 저장하기
  app/services/user_service.py
Labels: feat

#67 Fix[#66]: 장르로 임베딩 생성 시 name mapper 사용하도록 수정
  app/services/embedding_service.py
Labels: fix

#72 feat[#68]: 상태 업데이트 및 예외 로그 남기는 플로우 구현
  app/logger/__init__.py
  app/main.py
  app/repositories/action_log_repository.py
  app/services/consumer.py
  app/services/user_service.py
Labels: feat

#76 Chore[#75]: 에러 로그 수집을 위한 promtail 설정
  .github/workflows/cd.yml
  docker-compose.yml
  promtail-config.yml
Labels: chore, CI/CD, infra

#80 Chore[#79]: 임베딩 모델 교체
  .env.local
  .github/workflows/ci.yml
  .gitignore
  app/models/db_w2v_mapper.py
  app/models/word2vec_model.py
  app/tests/__init__.py
  app/tests/test_embedding_router.py
  app/tests/test_embedding_service.py
Labels: chore

#84 Refactor[#83]: 기존 데일리 스케줄러 삭제
  app/main.py
  app/router/scheduler_router.py
  app/services/scheduler_service.py
Labels: refactor
